kind: pipeline
name: default
steps:
- name: build
  image: microsoft/dotnet:2.2-sdk
  commands:
  - dotnet restore
  - dotnet build
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dev
branches: master