kind: pipeline
name: default
steps:
- name: build
  image: microsoft/dotnet:2.2-sdk
  commands:
  - dotnet restore
  - dotnet build

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dev
    username: Drone
    icon_url: https://drone.io/images/logo-d3343d0a14.svg
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded, please see {{build.link}}
      {{else}}
        Build {{build.number}} failed, please see {{build.link}}
      {{/success}}


branches: master
